language: python
python:
  - 3.6.0
env:
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1
services: postgresql
addons:
  postgresql: '9.6'
env:
   - DATABASE_URL=postgres://postgres@localhost/djangoapidb
install:
  - pip install pipenv
  - pipenv install
before_script:
  - psql -c "CREATE DATABASE djangoapidb;" -U postgres
  - pipenv run python manage.py migrate
  - pipenv run python manage.py collectstatic --no-input
script:
  - pipenv run python manage.py test