language: python
python:
  - "3.6"
  - "3.7-dev"
services: postgresql
addons:
  postgresql: '9.6'
env:
   - DATABASE_URL=postgres://postgres@localhost/djangoapidb
install:
  - pip install pipenv
  - pipenv install
before_script:
  - psql -c "CREATE DATABASE djangoapidb;" -U postgres
  - pipenv run python manage.py migrate
script:
  - pipenv run python manage.py test
